### ISSUE TITLE
No ATVdetails if reload_jobs fail

### ISSUE THREAD

**Issue by StefanoSnoopy** [dkmur/Stats#122]
Not a real issue, but I will point it out. 
Occurs when reload_jobs fails, for example for a missing "," even if in another .json file.
Rows with origins and NULL values ​​are inserted, but subsequently they are not UPDATED with details
https://github.com/dkmur/Stats/blob/307d8eb6667d7c19c16d0591732950fe2a01adce/cron_files/atvdetails.sh#L17

There is probably an extra "/" here as well, but it doesn't bother the script
https://github.com/dkmur/Stats/blob/307d8eb6667d7c19c16d0591732950fe2a01adce/default_files/config.ini.example#L15

Sorry for the lazy report

**Comment by StefanoSnoopy** [comment]
Something like this could be added to clean up the tables from failed jobs or missing pieces.
```sql
DELETE FROM ATVgeneral WHERE arch IS NULL AND productmodel IS NULL;
DELETE FROM ATVpd WHERE auth_username IS NULL AND auth_password IS NULL;
DELETE FROM ATVrgc WHERE auth_username IS NULL AND auth_password IS NULL;
DELETE FROM ATVvm WHERE bootdelay IS NULL AND gzip IS NULL;
```
Probably a WHERE field is enough ... two just to be sure
Inserted `bootdelay` and `gzip` are `''` not `NULL`

**Comment by dkmur** [comment]
> Not a real issue, but I will point it out. Occurs when reload_jobs fails, for example for a missing "," even if in another .json file. Rows with origins and NULL values ​​are inserted, but subsequently they are not UPDATED with details
> 
> https://github.com/dkmur/Stats/blob/307d8eb6667d7c19c16d0591732950fe2a01adce/cron_files/atvdetails.sh#L17
> 
> There is probably an extra "/" here as well, but it doesn't bother the script
> 
> https://github.com/dkmur/Stats/blob/307d8eb6667d7c19c16d0591732950fe2a01adce/default_files/config.ini.example#L15
> 
> Sorry for the lazy report

1 reload: so the reload fails for whatever reason, why aren't the jobs started in your case as every day we will copy atvdetails.json?

2 extra /: yes this is stupid but should have no effect, never to the time to correct it

**Comment by dkmur** [comment]
> Something like this could be added to clean up the tables from failed jobs or missing pieces.
> 
> ```sql
> DELETE FROM ATVgeneral WHERE arch IS NULL AND productmodel IS NULL;
> DELETE FROM ATVpd WHERE auth_username IS NULL AND auth_password IS NULL;
> DELETE FROM ATVrgc WHERE auth_username IS NULL AND auth_password IS NULL;
> DELETE FROM ATVvm WHERE bootdelay IS NULL AND gzip IS NULL;
> ```
> 
> Probably a WHERE field is enough ... two just to be sure Inserted `bootdelay` and `gzip` are `''` not `NULL`

Your point is valid, downside of doing so is it might appear that everything is working fine (as there are no NULLL values) where in fact i.e. a few devices fail every night and tis isn't noticed. I could add the option to config.ini to clean atvdetails for missing data but would opt to default it to false

**Comment by StefanoSnoopy** [comment]
ok.. probably there's something else.

jobs are loaded and executed correctly. new rows are populated with dates and origins, but are not updated with jobs results after

![image](https://user-images.githubusercontent.com/3732678/153709135-8f9c5c5a-b61d-4beb-9ee6-2fef00647343.png)
Populated rows are from script launched manually to test (not daily from cron) 🤷‍♂️
I look closer and let you know

**Comment by dkmur** [comment]
> ok.. probably there's something else.
> 
> jobs are loaded and executed correctly. new rows are populated with dates and origins, but are not updated with jobs results after
> 
> ![image](https://user-images.githubusercontent.com/3732678/153709135-8f9c5c5a-b61d-4beb-9ee6-2fef00647343.png) Populated rows are from script launched manually to test (not daily from cron) 🤷‍♂️ I look closer and let you know

1 you could try add a bit more delay in processing the jobs to db in Stats config.ini
2 in mad config.ini you could have a look at `job_thread_count: 5           # Amount of threads to work off the device jobs. Default: 2.`

**Comment by StefanoSnoopy** [comment]
> Your point is valid, downside of doing so is it might appear that everything is working fine (as there are no NULLL values) where in fact i.e. a few devices fail every night and tis isn't noticed. I could add the option to config.ini to clean atvdetails for missing data but would opt to default it to false
you're right. also tables are "clear" but graph are "strange"
blu=NULL 
![image](https://user-images.githubusercontent.com/3732678/153751555-d738902b-cc25-4d87-ae0f-f72de047a040.png)

**Comment by StefanoSnoopy** [comment]
It's working again 🤷‍♂️
> 1 you could try add a bit more delay in processing the jobs to db in Stats config.ini
this was alredy calibrated
> 2 in mad config.ini you could have a look at job_thread_count: 5 # Amount of threads to work off the device jobs. Default: 2.
This is a good advice, I hadn't noticed this before. I changed it but I don't think that's why it's back to working again 

until yesterday if I manually ran `./atvdetail.sh` the tables were updated, they were not updated if the script started with cron
I don't know anything anymore.😢
